# Generated by Django 3.2.16 on 2023-05-11 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230511_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное количество - 1.')], verbose_name='Количество ингредиента'),
        ),
    ]
